name: gha_example:GitHub Action exercise 

# Szablon workflow: Miejsca oznaczone "#" naley uzupełnić 

on:
  workflow_dispatch:
#  push:
#    branches: [ master ]

jobs:
  build:
    # Definicja systemu do instalacji na wźle roboczym 
    runs-on: ubuntu-latest
    
    steps:

      # Instalacja środowiska Docker + Buildx
      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2
        
      # Instalacja QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      # Logowanie do Dockerhub-a
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # Budowa obrazu dla dwóch architektur sprzętowych 
      # oraz przesłanie do własnego repo na Dockerhub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile_dev
          platforms: linux/arm64/v8,linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
          tags: |
            798483003/endlab:ghlab10extendedautomate
      
